services:
  logging-service:
    container_name: wishes-logging-service
    build: ./Logging
    depends_on:
      logging-postgres-db:
        condition: service_healthy
#      auth-service:
#        condition: service_started
      config-service:
        condition: service_healthy

    ports:
      - ${LOGGING_SERVICE_EXTERNAL_PORT}

    env_file:
      - shared.env
      - .security/logging.env
    environment:
      POSTGRES_DATASOURCE_URL: jdbc:postgresql://logging-postgres-db:${DB_INNER_PORT}/cohenrol_logging_db
#      SPRING_CLOUD_CONFIG_NAME: logging-service

##################### DATABASE ########################################
  logging-postgres-db:
    container_name: wishes-logging-database
    image: postgres:latest

    env_file: shared.env
    environment:
      POSTGRES_DB: cohenrol_logging_db

    ports:
      - ${LOGGING_DB_EXTERNAL_PORT}

    volumes:
      - logging-db-data:/var/lib/postgresql

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U cohenrol -d cohenrol_logging_db" ]
      interval: 5s
      timeout: 5s
      retries: 5