include:
  - docker-compose-auth.yml
  - docker-compose-config.yml
  - docker-compose-nginx.yml
  - docker-compose-logging.yml
  - docker-compose-profile.yml
  - docker-compose-wish.yml

volumes:
  auth-db-data:
  logging-db-data:
  wish-db-data:
  profile-db-data:

#networks:
#  wishes-network:
#    name: wishes-shared-network