package ru.cohenrol.loggingservice.logging.enums;

public enum LogReason {
    REGISTRATION, LOGIN, REFRESH, LOGOUT,

//    COURSE_ENROLLMENT, COURSE_CANCELLATION,
//
//    EXTERNAL_PROGRESS_SERVICE_ERROR,
//    EXTERNAL_COURSES_SERVICE_ERROR,
//    EXTERNAL_LOGGING_SERVICE_ERROR,
//
//    INTERNAL_ENROLLMENT_ALREADY_CANCELLED_ERROR,
//    INTERNAL_ENROLLMENT_ALREADY_EXISTS_ERROR,
//    INTERNAL_ENROLLMENT_NOT_FOUND_ERROR,

    OTHER,
}
