server {
    listen 80;
    server_name localhost;

### Authentication Service ###

     location /api/v1/public/auth {
         proxy_pass http://auth-service:8080;
         proxy_set_header Host $host;
         proxy_set_header X-Real-IP $remote_addr;
         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
     }

     location /api/v1/private/auth {
         proxy_pass http://auth-service:8080;
         proxy_set_header Host $host;
         proxy_set_header X-Real-IP $remote_addr;
         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
     }

### Logging Service ###

    location /api/v1/private/logs {
        proxy_pass http://logging-service:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}